package com.faceverify.app.data

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.util.Base64
import kotlin.math.abs
import kotlin.math.sqrt

/** Golden-vector test: Protect.kt must be bit-compatible with the server's
 *  biometric/core/protect.py (fixture generated by it). If this fails, synced
 *  protected templates will not match live captures - do not ship. */
class ProtectTest {

    private fun fixture(): JSONObject {
        val text = javaClass.classLoader!!.getResourceAsStream("protect_fixture.json")!!
            .readBytes().toString(Charsets.UTF_8)
        return JSONObject(text)
    }

    @Test
    fun matchesServerGoldenVectors() {
        val fx = fixture()
        assertEquals(Protect.SCHEME, fx.getString("scheme"))
        val cases = fx.getJSONArray("cases")
        for (c in 0 until cases.length()) {
            val case = cases.getJSONObject(c)
            val seed = Base64.getDecoder().decode(case.getString("seed"))
            val inArr = case.getJSONArray("input")
            val expArr = case.getJSONArray("expected")
            val input = FloatArray(inArr.length()) { inArr.getDouble(it).toFloat() }
            val out = Protect.project(seed, input)
            assertEquals("padded length (dim ${input.size})", expArr.length(), out.size)
            for (i in out.indices) {
                assertTrue(
                    "dim ${input.size} idx $i: ${out[i]} vs ${expArr.getDouble(i)}",
                    abs(out[i] - expArr.getDouble(i).toFloat()) < 1e-4f,
                )
            }
        }
    }

    @Test
    fun preservesCosineWithinDomain() {
        val seed = ByteArray(32) { it.toByte() }
        val rnd = java.util.Random(42)
        val a = FloatArray(512) { rnd.nextGaussian().toFloat() }.normalized()
        val b = FloatArray(512) { rnd.nextGaussian().toFloat() }.normalized()
        val pa = Protect.project(seed, a)
        val pb = Protect.project(seed, b)
        assertTrue(abs(dot(pa, pb) - dot(a, b)) < 1e-4f)
        assertTrue(abs(dot(pa, pa) - 1f) < 1e-4f)
    }

    @Test
    fun differentSeedsAreUnlinkable() {
        val rnd = java.util.Random(7)
        val v = FloatArray(512) { rnd.nextGaussian().toFloat() }.normalized()
        val p1 = Protect.project(ByteArray(32) { 1 }, v)
        val p2 = Protect.project(ByteArray(32) { 2 }, v)
        assertTrue(abs(dot(p1, p2)) < 0.3f)
    }

    private fun dot(a: FloatArray, b: FloatArray): Float {
        var s = 0f
        for (i in a.indices) s += a[i] * b[i]
        return s
    }

    private fun FloatArray.normalized(): FloatArray {
        var n = 0f
        for (f in this) n += f * f
        val inv = 1f / sqrt(n)
        return FloatArray(size) { this[it] * inv }
    }
}
