package com.faceverify.app.credential

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.util.Base64

/** Golden-credential test: the Kotlin verifier must accept exactly what the
 *  server issues (fixture generated by biometric/core/credential.py) and fail
 *  closed on tamper / wrong key / expiry / unknown issuer. If this fails, the
 *  Android verifier and the server disagree — do not ship. */
class CredentialVerifierTest {

    private val fx: JSONObject by lazy {
        JSONObject(javaClass.classLoader!!.getResourceAsStream("credential_fixture.json")!!
            .readBytes().toString(Charsets.UTF_8))
    }

    private val pk: ByteArray get() = Base64.getDecoder().decode(fx.getString("public_key"))
    private val now: Long get() = fx.getLong("iat") + 60

    private fun holder(): FloatArray {
        val a = fx.getJSONArray("holder_embedding")
        return FloatArray(a.length()) { a.getDouble(it).toFloat() }
    }

    private fun stranger(): FloatArray {
        val a = fx.getJSONArray("stranger_embedding")
        return FloatArray(a.length()) { a.getDouble(it).toFloat() }
    }

    @Test
    fun verifiesServerIssuedCredentialAndMatchesHolder() {
        val p = CredentialVerifier.verify(fx.getString("credential"),
            { iss, kid -> if (iss == fx.getString("issuer") && kid == fx.getString("kid")) pk else null },
            nowSec = now)
        assertEquals(fx.getString("subject"), p.subject)
        assertEquals(fx.getString("name"), p.name)
        assertEquals(fx.getString("cid_hex"), p.cid.joinToString("") { "%02x".format(it) })
        assertEquals(listOf("face"), p.modalities)
        assertTrue(CredentialVerifier.match(p, "face", holder()) >
            fx.getDouble("expected_holder_score_min").toFloat())
        assertTrue(CredentialVerifier.match(p, "face", stranger()) <
            fx.getDouble("expected_stranger_score_max").toFloat())
    }

    private fun expectCode(code: String, block: () -> Unit) {
        try {
            block()
            throw AssertionError("expected CredentialException $code")
        } catch (e: CredentialVerifier.CredentialException) {
            assertEquals(code, e.code)
        }
    }

    @Test
    fun failsClosed() {
        val text = fx.getString("credential")
        // unknown issuer
        expectCode("unknown_issuer") {
            CredentialVerifier.verify(text, { _, _ -> null }, nowSec = now)
        }
        // wrong key
        expectCode("bad_signature") {
            CredentialVerifier.verify(text, { _, _ -> ByteArray(32) { 7 } }, nowSec = now)
        }
        // expired
        expectCode("credential_expired") {
            CredentialVerifier.verify(text, { _, _ -> pk }, nowSec = fx.getLong("exp") + 1)
        }
        // bit-flip inside the payload
        val body = text.substring(4).toCharArray()
        body[20] = if (body[20] == '0') '1' else '0'
        try {
            CredentialVerifier.verify("FV1:" + String(body), { _, _ -> pk }, nowSec = now)
            throw AssertionError("tampered credential must not verify")
        } catch (e: CredentialVerifier.CredentialException) {
            assertTrue(e.code == "bad_signature" || e.code == "malformed_credential"
                || e.code == "unknown_issuer")
        } catch (e: IllegalArgumentException) {
            // base45 rejects the flip — also fail-closed
        }
        // not a credential at all
        expectCode("malformed_credential") {
            CredentialVerifier.verify("HC1:NOPE", { _, _ -> pk }, nowSec = now)
        }
    }
}
