package com.faceverify.app.credential

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/** Golden trust-store test: TrustData must accept exactly what /v1/trust-store
 *  serves (fixture generated by the server code), resolve issuer keys, honour
 *  exact AND Bloom revocation lists (no false negatives), and reject tamper. */
class TrustDataTest {

    private val fx: JSONObject by lazy {
        JSONObject(javaClass.classLoader!!.getResourceAsStream("trust_store_fixture.json")!!
            .readBytes().toString(Charsets.UTF_8))
    }
    private val resp: JSONObject get() = fx.getJSONObject("response")

    private fun parse(): TrustData = TrustData.verifyAndParse(
        resp.getString("payload_b64"), resp.getString("sig"), resp.getString("root_key"))

    @Test
    fun parsesAndResolvesIssuerKeys() {
        val t = parse()
        assertEquals(2, t.issuerCount)
        assertNotNull(t.resolve("org_exact", fx.getString("issuer_kid")))
        assertNotNull(t.resolve("org_bloom", fx.getString("issuer_kid")))
        assertNull(t.resolve("org_exact", "0000000000000000"))
        assertNull(t.resolve("stranger_org", fx.getString("issuer_kid")))
    }

    @Test
    fun revocationExactAndBloom() {
        val t = parse()
        assertTrue(t.isRevoked("org_exact", fx.getString("revoked_exact")))
        assertFalse(t.isRevoked("org_exact", fx.getString("clean_cid")))
        assertTrue(t.isRevoked("org_bloom", fx.getString("revoked_bloom")))
        assertFalse(t.isRevoked("org_bloom", fx.getString("clean_cid")))
        assertFalse(t.isRevoked("stranger_org", fx.getString("revoked_exact")))
    }

    @Test
    fun bloomHasNoFalseNegatives() {
        val t = parse()
        // every revoked bloom cid (1000..1149) must hit
        for (i in 0 until 150) {
            val cid = "%032x".format(1000 + i)
            assertTrue("cid $cid must be revoked", t.isRevoked("org_bloom", cid))
        }
    }

    @Test
    fun rejectsTamperAndWrongRoot() {
        val payload = resp.getString("payload_b64")
        val sig = resp.getString("sig")
        val root = resp.getString("root_key")
        // flip one byte of the payload
        val bytes = java.util.Base64.getDecoder().decode(payload)
        bytes[40] = (bytes[40].toInt() xor 1).toByte()
        val tampered = java.util.Base64.getEncoder().encodeToString(bytes)
        try {
            TrustData.verifyAndParse(tampered, sig, root)
            throw AssertionError("tampered trust store must not parse")
        } catch (e: IllegalArgumentException) { /* expected */ }
        // wrong root key
        val otherRoot = java.util.Base64.getEncoder().encodeToString(ByteArray(32) { 9 })
        try {
            TrustData.verifyAndParse(payload, sig, otherRoot)
            throw AssertionError("wrong root must not verify")
        } catch (e: IllegalArgumentException) { /* expected */ }
    }
}
