"""Deploy this repo to a Hugging Face **Gradio** Space (free accounts can't use Docker).

    .\\venv\\Scripts\\python deploy-space.py --space kyereboatengcaleb/verification

It builds a single clean orphan commit containing the app plus the three files a
Gradio Space needs, and force-pushes it:

    README.md          front matter rewritten to sdk: gradio, app_file: space_app.py
    requirements.txt   the SERVICE deps (the repo's own requirements.txt is the full
                       dev set - torch, jax and friends - which would blow the build)
    packages.txt       apt libs OpenCV/MediaPipe need, the ones the Dockerfile installs

Left out of the deploy commit, as with deploy-hf.ps1: the android/ app, the bundled
.onnx anti-spoof models and the palm .task binary (Spaces reject committed binaries;
space_app.py fetches the models at boot instead).

The working branch is restored afterwards. Nothing here touches your local history.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys

BRANCH = "space-deploy"

PACKAGES = """\
libglib2.0-0
libgomp1
libgl1
libsm6
libxext6
libxrender1
libxcb1
libegl1
libgles2
"""

FRONT_MATTER = """\
---
title: {title}
emoji: 🟣
colorFrom: indigo
colorTo: purple
sdk: gradio
sdk_version: 4.44.0
app_file: space_app.py
pinned: false
short_description: Contactless face & palm identity — offline, on any phone
---
"""


def run(*args: str, check: bool = True) -> str:
    r = subprocess.run(args, capture_output=True, text=True)
    if check and r.returncode != 0:
        raise SystemExit(f"$ {' '.join(args)}\n{r.stdout}{r.stderr}")
    return r.stdout.strip()


def build_readme(title: str) -> str:
    """Repo README with its Docker front matter swapped for the Gradio one."""
    with open("README.md", encoding="utf-8") as fh:
        body = fh.read()
    body = re.sub(r"\A---\n.*?\n---\n", "", body, flags=re.S)   # drop existing block
    return FRONT_MATTER.format(title=title) + body


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--space", required=True, help="e.g. user/verification")
    ap.add_argument("--remote", default="gspace", help="git remote name to use")
    ap.add_argument("--title", default="Biometric Verify")
    a = ap.parse_args()

    if run("git", "status", "--porcelain"):
        raise SystemExit("commit or stash your changes first - this pushes a clean tree.")
    work = run("git", "branch", "--show-current")
    url = f"https://huggingface.co/spaces/{a.space}"
    if a.remote not in run("git", "remote").split():
        run("git", "remote", "add", a.remote, url)
    else:
        run("git", "remote", "set-url", a.remote, url)

    run("git", "branch", "-D", BRANCH, check=False)
    run("git", "checkout", "--orphan", BRANCH)
    try:
        with open("README.md", "w", encoding="utf-8") as fh:
            fh.write(build_readme(a.title))
        with open("packages.txt", "w", encoding="utf-8") as fh:
            fh.write(PACKAGES)
        with open("requirements-service.txt", encoding="utf-8") as src:
            service_deps = src.read()
        with open("requirements.txt", "w", encoding="utf-8") as dst:
            dst.write("# Generated by deploy-space.py - the Space installs THIS file.\n"
                      "# Source: requirements-service.txt (no fingerprint/dev stack).\n")
            dst.write(service_deps)
        run("git", "add", "-A")
        # Drop what a Space rejects or doesn't need — AFTER staging, or `add -A`
        # simply puts the binaries back and the push is refused.
        run("git", "rm", "--cached", "--ignore-unmatch", "-q",
            "face/models/antispoof_bin_1.5_128.onnx",
            "face/models/antispoof_print_replay_1.5_128.onnx",
            "palm/models/hand_landmarker.task")
        run("git", "rm", "-r", "--cached", "--ignore-unmatch", "-q", "android")
        # Disposable deploy artifact; don't require the GPG passphrase.
        run("git", "-c", "commit.gpgsign=false", "commit", "-q", "-m",
            "Deploy to Hugging Face Space")
        print(run("git", "push", "--force", a.remote, f"{BRANCH}:main"))
        print(f"\nDeployed to {url}\nWatch the build under the Space's Logs tab.")
    finally:
        run("git", "checkout", "-f", work)
        run("git", "branch", "-D", BRANCH, check=False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
